title: Yi Wang's Homepage
page-top-title: Welcome
top-section-bg-text: Aspiring Data Analyst
home-subtitle: Yi Wang&ensp;|&ensp;New graduate in Statistics 
copyright-text: '&copy; Yi Wang. All Rights Reserved.'
